version: "3.3"
services:
  redis:
    image: redis:6.2.0
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_insight_volume_data:/db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"

volumes:
  redis_volume_data:
  redis_insight_volume_data:
